name: Test CodeCraft Page

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get page
        run: |
          curl -L --max-time 30 https://codecraftsupport.com/Kirby/gallery_specials.html
